-- Migration 027 — extend agent_briefs into a general "inbox" surface
--
-- Context: until now agent_briefs only held ad-action cards generated by the
-- /api/cron/agent-briefs nightly run. We're growing it into a single inbox
-- that any agent / watcher can write to (ROAS drops per market, competitor
-- price changes, customer cohort risks, etc.) so the user has one feed
-- instead of multiple dashboards to scan.
--
-- Changes are strictly additive + relaxed CHECK constraints, so the existing
-- nightly cron keeps working without modification.
--
-- New surface area:
--   - source_agent           which agent / watcher created the card
--   - assigned_to            future role-based routing (nullable = broadcast)
--   - snoozed_until          "remind me later" support
--   - store_id               for market-level cards (target_type='market')
--   - outcome_*              7-day revisit loop ("did this help?")
--
-- Existing constraint changes:
--   - integration_account_id becomes NULLABLE — a market-level ROAS card
--     blends multiple Meta bindings and has no single owning account.
--   - target_type CHECK relaxed to include 'market', 'store', 'product',
--     'customer', 'competitor' (room to grow without another migration).
--   - severity CHECK relaxed to include 'info' for low-severity informational
--     cards that should NOT page the user but DO belong in the feed.

-- ============================================================
-- Relax constraints
-- ============================================================

ALTER TABLE agent_briefs
  ALTER COLUMN integration_account_id DROP NOT NULL;

ALTER TABLE agent_briefs
  DROP CONSTRAINT agent_briefs_target_type_check;

ALTER TABLE agent_briefs
  ADD CONSTRAINT agent_briefs_target_type_check
  CHECK (target_type IN ('ad', 'adset', 'campaign', 'market', 'store', 'product', 'customer', 'competitor'));

ALTER TABLE agent_briefs
  DROP CONSTRAINT agent_briefs_severity_check;

ALTER TABLE agent_briefs
  ADD CONSTRAINT agent_briefs_severity_check
  CHECK (severity IN ('red', 'amber', 'green', 'info'));

-- ============================================================
-- New columns
-- ============================================================

ALTER TABLE agent_briefs
  ADD COLUMN source_agent     TEXT,                       -- 'ads-intel' | 'watcher-roas' | 'morning-report' | ...
  ADD COLUMN assigned_to      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN snoozed_until    TIMESTAMPTZ,
  ADD COLUMN store_id         UUID REFERENCES stores(id) ON DELETE CASCADE,
  ADD COLUMN outcome_status   TEXT DEFAULT 'pending'
    CHECK (outcome_status IN ('pending', 'measuring', 'succeeded', 'failed', 'inconclusive', 'na')),
  ADD COLUMN outcome_metric            TEXT,              -- 'roas' | 'spend' | 'revenue' | 'orders' | …
  ADD COLUMN outcome_baseline_value    NUMERIC(14,4),
  ADD COLUMN outcome_current_value     NUMERIC(14,4),
  ADD COLUMN outcome_revisit_at        TIMESTAMPTZ,       -- when the outcome cron should re-evaluate
  ADD COLUMN outcome_summary           TEXT,              -- human-readable result line
  ADD COLUMN outcome_evaluated_at      TIMESTAMPTZ;

-- ============================================================
-- Indexes for the new query patterns
-- ============================================================

-- Inbox feed: "pending non-snoozed cards for the org, newest first"
CREATE INDEX idx_agent_briefs_inbox
  ON agent_briefs (organization_id, status, severity, created_at DESC)
  WHERE status IN ('pending', 'acknowledged');

-- Outcomes cron: "cards waiting for a revisit"
CREATE INDEX idx_agent_briefs_outcome_revisit
  ON agent_briefs (outcome_revisit_at)
  WHERE outcome_status IN ('pending', 'measuring')
    AND outcome_revisit_at IS NOT NULL;

-- Per-store filter on the inbox page
CREATE INDEX idx_agent_briefs_store
  ON agent_briefs (store_id, for_date DESC)
  WHERE store_id IS NOT NULL;

-- ============================================================
-- Cron idempotency for non-Meta cards
-- ============================================================
--
-- The existing UNIQUE (integration_account_id, for_date, target_type, target_id)
-- doesn't fire for market-level cards because integration_account_id is NULL.
-- Add a partial unique index keyed on (organization_id, for_date, target_type,
-- target_id) for the NULL-account case so the new watchers stay idempotent.

CREATE UNIQUE INDEX idx_agent_briefs_unique_org_target
  ON agent_briefs (organization_id, for_date, target_type, target_id)
  WHERE integration_account_id IS NULL;

-- ============================================================
-- RLS for new cards without an integration_account
-- ============================================================
--
-- The existing SELECT policy joins through integration_accounts. Cards with
-- a NULL integration_account_id (market-level, store-level) need a separate
-- path that joins through stores OR falls back to organization_id directly.

CREATE POLICY "Members can view org-scoped briefs"
  ON agent_briefs FOR SELECT
  USING (
    integration_account_id IS NULL
    AND organization_id IN (SELECT user_org_ids())
  );

-- Writes stay service-role only.

-- ============================================================
-- Comments
-- ============================================================

COMMENT ON COLUMN agent_briefs.source_agent IS
  'Producer of the card. Used to filter the inbox and to attribute outcomes back to a specific agent for trust-score tracking.';

COMMENT ON COLUMN agent_briefs.outcome_status IS
  'pending = waiting for action; measuring = action taken, outcome unknown; succeeded/failed/inconclusive = after revisit_at evaluation; na = informational card with no measurable outcome.';

COMMENT ON COLUMN agent_briefs.outcome_revisit_at IS
  'When the /api/cron/inbox-outcomes job should re-measure outcome_metric and compare to outcome_baseline_value.';

COMMENT ON COLUMN agent_briefs.snoozed_until IS
  'Hide from the default inbox feed until this timestamp. Set by the snooze action; status stays "pending".';
